  version: '3.8'

  services:
    postgres:
      image: postgres:15-alpine
      container_name: online_shop_db
      restart: unless-stopped
      env_file:
        - .env.development
      environment:
        POSTGRES_DB: ${DATABASE_NAME:-online-shop-db}
        POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
        POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      ports:
        - "${DATABASE_PORT:-5433}:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      networks:
        - online_shop_network

    

  volumes:
    postgres_data:
      driver: local
    redis_data:
      driver: local

  networks:
    online_shop_network:
      driver: bridge
